/* ----------------------------------------------------------------------------------------
* Autor....: Guilherme Kaiser - Deloitte
* Projeto..: Vivo - VALENTINA
* Descrição: script criado para teste da criação de palitos automáticos RELEASE JULHO 2024
* Data.....: 24/04/2024
*  ----------------------------------------------------------------------------------------
*/
@isTest
public class CreateTopicsAutoReleaseJulho2024Test {

    @isTest
    public  static void testCreateTopicsAutoReleaseJulho2024(){
      CreateTopicsAutoReleaseJulho2024 topicAuto = new CreateTopicsAutoReleaseJulho2024();
	}
}