/* -------------------------------------------------------------------------
* Autor....: Guilherme Kaiser - Deloitte
* Projeto..: Vivo - VALENTINA
* Descrição: script criado para teste da criação de palitos automáticos
* Data.....: 10/04/2024
*  -------------------------------------------------------------------------
*/
@isTest
public class CreateTopicsAutoBloco9Test {

    @isTest
    public  static void testCreateTopicsAutoBloco9(){
		CreateTopicsAutoBloco9 topicAuto = new CreateTopicsAutoBloco9();
	}
}