/* ----------------------------------------------------------------------------------------
* Autor....: Guilherme Kaiser - Deloitte
* Projeto..: Vivo - VALENTINA
* Descrição: script criado para teste da criação de palitos automáticos RELEASE SETEMBRO 2024
* Data.....: 27/05/2024
*  ----------------------------------------------------------------------------------------
*/
@isTest
public class CreateTopicsAutoReleaseSetembro2024Test {

    @isTest
    public  static void testCreateTopicsAutoReleaseSetembro2024(){
      CreateTopicsAutoReleaseSetembro2024 topicAuto = new CreateTopicsAutoReleaseSetembro2024();
	}
}