public class DisputeChargeModel {
    
    @AuraEnabled
    public String uniqueId;
    
    @AuraEnabled
    public String type;

    @AuraEnabled
	public String totalAmount;

    @AuraEnabled
    public String subscriberId;
    
    @AuraEnabled
    public String startDate;

    @AuraEnabled
    public String offerType;

    @AuraEnabled
    public String offerId;

    @AuraEnabled
    public String name;

    @AuraEnabled
    public String id;

    @AuraEnabled
    public String frontEndCode;

    @AuraEnabled
    public String endDate;

    @AuraEnabled
    public String comboIndicator;

    @AuraEnabled
    public String codeDescription;

    @AuraEnabled
    public String code;

    @AuraEnabled
    public String bundleId;

    @AuraEnabled
    public String availableAmount;

    @AuraEnabled
    public String discount;

    @AuraEnabled
    public String ChargeCategory;
    
    @AuraEnabled
    public String instance;
    
    @AuraEnabled
    public String csp;
    
    @AuraEnabled
    public String cspOperatorName;
    
    @AuraEnabled
    public String startTime;

    @AuraEnabled
    public String haveDiscount;

    @AuraEnabled
    public String customerAccountId;
}