/*
    Discontinued. Technical debt: to be removed!

    ---------------------------------------------------
    @author - Márcio Las
    @company - Telefonica  
    @date - 05/05/2022
    @description - Class Service for SSMAttendanceEndService
    ---------------------------------------------------
*/
public with sharing class SSMAttendanceEndServiceService {
    // For testing purposes only
    public static String getTestingPurposesOnlyMessage() {
        return (SSMAttendanceEndServiceEngine.getTestingPurposesOnlyMessage());
    }

    /* 
    public static Map<String, Object> loadSSMAttendanceEndService() {
        return (SSMAttendanceEndServiceEngine.loadSSMAttendanceEndService());
    }
    */
}
