/*
    Discontinued. Technical debt: to be removed!

    ---------------------------------------------------
    @author - Márcio Las
    @company - Telefonica  
    @date - 04/05/2022
    @description - Class Service for SSMAttendanceCustomerData
    ---------------------------------------------------
*/
public with sharing class SSMAttendanceCustomerDataService {
    // For testing purposes only
    public static String getTestingPurposesOnlyMessage() {
        return (SSMAttendanceCustomerDataEngine.getTestingPurposesOnlyMessage());
    }

    /* 
    public static Map<String, Object> loadSSMAttendanceCustomerData() {
        return (SSMAttendanceCustomerDataEngine.loadSSMAttendanceCustomerData());
    }
    */
}
