public class WorkOrderItemObject {

    @AuraEnabled
    @InvocableVariable
    public String id;
    @AuraEnabled
    @InvocableVariable
    public String state;
    @AuraEnabled
    @InvocableVariable
    public String stateReason;
    @AuraEnabled
    @InvocableVariable
    public String country;
    @AuraEnabled
    @InvocableVariable
    public String city;
    @AuraEnabled
    @InvocableVariable
    public String stateOrProvince;
    @AuraEnabled
    @InvocableVariable
    public String locality;
    @AuraEnabled
    @InvocableVariable
    public String postcode;
    @AuraEnabled
    @InvocableVariable
    public String streetType;
    @AuraEnabled
    @InvocableVariable
    public String streetPrefix;
    @AuraEnabled
    @InvocableVariable
    public String streetName;
    @AuraEnabled
    @InvocableVariable
    public String streetNr;
    @AuraEnabled
    @InvocableVariable
    public String streetCode;
    @AuraEnabled
    @InvocableVariable
    public String cnl;
    @AuraEnabled
    @InvocableVariable
    public String networkOwner;
    @AuraEnabled
    @InvocableVariable
    public String externalNetworkOwner;
    @AuraEnabled
    @InvocableVariable
    public String telephonicArea;
    @AuraEnabled
    @InvocableVariable
    public String centralOffice;
    @AuraEnabled
    @InvocableVariable
    public String microArea;
    @AuraEnabled
    @InvocableVariable
    public String workSpecification;
    @AuraEnabled
    @InvocableVariable
    public String appointmentId;
    @AuraEnabled
    @InvocableVariable
    public String appointmentDescription;
    @AuraEnabled
    @InvocableVariable
    public DateTime appointmentStartDateTime;
    @AuraEnabled
    @InvocableVariable
    public DateTime appointmentEndDateTime;
    @AuraEnabled
    @InvocableVariable
    public String appointmentState;

}